spring:
  datasource:
    url: jdbc:postgresql://localhost:5232/smartAlert_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

# Service account location can be a filesystem path or a classpath resource
gcp:
  firebase:
    service-account: classpath:firebase-service-account.json
    database-url: ${FIREBASE_URL}